name: gy
description: "adb tool for windows, macos, linux"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  logger: ^2.5.0
  desktop_window: ^0.4.2
  file_selector: ^1.0.3
  collection: ^1.18.0
  desktop_drop: ^0.5.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/bin/windows/
    - assets/bin/macos/
    - assets/bin/linux/
