name: Flutter Windows Build

on:
  push:
    branches:
      - main # 监听 main 分支的提交
  pull_request:
    branches:
      - main # 监听对 main 分支的 PR

jobs:
  build-windows:
    name: Build Flutter Windows App
    runs-on: windows-latest # 使用 Windows 运行环境

    steps:
      # 1. 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 设置 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0" # 使用 Flutter 的稳定版本
          channel: stable

      # 3. 获取依赖
      - name: Install Dependencies
        run: flutter pub get

      # 4. 打包 Windows 应用
      - name: Build Windows App
        run: flutter build windows --release

      # 5. 保存打包结果
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/
          if-no-files-found: warn
